# Generated by Django 3.2.5 on 2022-03-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_appointment_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='experience',
            field=models.CharField(default='1 year', max_length=10),
        ),
    ]
