# Generated by Django 3.2.5 on 2022-03-27 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_doctor_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 27, 15, 56, 13, 441841)),
        ),
    ]
