# Generated by Django 3.2.5 on 2022-03-29 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_patientuser_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='report',
            name='patientUser',
        ),
        migrations.AlterField(
            model_name='patientuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 29, 16, 16, 15, 654867)),
        ),
    ]
