# Generated by Django 3.2.5 on 2022-04-04 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0009_auto_20220329_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='patientuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='patientuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='patientuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='patientuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='patientuser',
            name='username',
        ),
        migrations.AddField(
            model_name='patientuser',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
