# Generated by Django 3.2.5 on 2022-04-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20220409_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_pic/doctor_profile_pic/'),
        ),
        migrations.AlterField(
            model_name='patientuser',
            name='profile_picture',
            field=models.ImageField(default='img/defaultuser.png', upload_to='media/profile_pic/user_profile_pic/'),
        ),
    ]
